import { ApiEndpointDefinition } from "@/types";

export const API_ENDPOINTS: ApiEndpointDefinition[] = [
  {
    id: "health",
    category: "Platform",
    method: "GET",
    pathTemplate: "/api/health",
    description: "Dependency health across Cosmos DB, Blob Storage, Key Vault, and Graph.",
    authScope: "public",
    verificationMode: "automated",
  },
  {
    id: "tenants-public",
    category: "Tenant Discovery",
    method: "GET",
    pathTemplate: "/api/tenants/public",
    description: "Public tenant list used before authentication.",
    authScope: "public",
    verificationMode: "automated",
  },
  {
    id: "tenants-lookup",
    category: "Tenant Discovery",
    method: "POST",
    pathTemplate: "/api/tenants/lookup",
    description: "Validates a tenant slug before login.",
    authScope: "public",
    verificationMode: "manual",
    sampleBody: '{\n  "slug": "{activeTenantSlug}"\n}',
  },
  {
    id: "auth-request-link",
    category: "Authentication",
    method: "POST",
    pathTemplate: "/api/auth/request-link",
    description: "Requests a one-time sign-in link for an authorized user.",
    authScope: "public",
    verificationMode: "manual",
    sampleBody: '{\n  "email": "operator@example.com",\n  "tenantSlug": "{activeTenantSlug}"\n}',
  },
  {
    id: "auth-password",
    category: "Authentication",
    method: "POST",
    pathTemplate: "/api/auth/password",
    description: "Performs a password-based login for a tenant context.",
    authScope: "public",
    verificationMode: "manual",
    sampleBody: '{\n  "email": "operator@example.com",\n  "password": "redacted",\n  "tenantSlug": "{activeTenantSlug}"\n}',
  },
  {
    id: "auth-verify",
    category: "Authentication",
    method: "GET",
    pathTemplate: "/api/auth/verify?token=sample-token",
    description: "Consumes a magic-link token and establishes a session.",
    authScope: "public",
    verificationMode: "manual",
  },
  {
    id: "auth-signout",
    category: "Authentication",
    method: "GET",
    pathTemplate: "/api/auth/signout",
    description: "Ends the active session and redirects to login.",
    authScope: "authenticated",
    verificationMode: "manual",
    destructive: true,
  },
  {
    id: "me",
    category: "Session",
    method: "GET",
    pathTemplate: "/api/me",
    description: "Returns the current user and active tenant permissions.",
    authScope: "authenticated",
    verificationMode: "automated",
  },
  {
    id: "me-profile",
    category: "Session",
    method: "GET",
    pathTemplate: "/api/me/profile",
    description: "Returns the signed-in user's safe profile details.",
    authScope: "authenticated",
    verificationMode: "automated",
  },
  {
    id: "me-profile-update",
    category: "Session",
    method: "PATCH",
    pathTemplate: "/api/me/profile",
    description: "Updates the signed-in user's self-service profile fields.",
    authScope: "authenticated",
    verificationMode: "manual",
    sampleBody:
      '{\n  "displayName": "Operator Example",\n  "jobTitle": "Program Manager",\n  "organization": "Aleut Federal"\n}',
  },
  {
    id: "me-password",
    category: "Session",
    method: "POST",
    pathTemplate: "/api/me/password",
    description: "Resets the signed-in user's password.",
    authScope: "authenticated",
    verificationMode: "manual",
    destructive: true,
    sampleBody:
      '{\n  "currentPassword": "redacted-current",\n  "nextPassword": "redacted-new-password"\n}',
  },
  {
    id: "sessions-current",
    category: "Session",
    method: "PATCH",
    pathTemplate: "/api/sessions/current",
    description: "Switches the active tenant stored in session state.",
    authScope: "authenticated",
    verificationMode: "manual",
    sampleBody: '{\n  "tenantId": "{activeTenantId}"\n}',
  },
  {
    id: "tenants-list",
    category: "Tenant Discovery",
    method: "GET",
    pathTemplate: "/api/tenants",
    description: "Lists tenants available to the current authenticated user.",
    authScope: "authenticated",
    verificationMode: "automated",
  },
  {
    id: "tenants-current",
    category: "Tenant Discovery",
    method: "GET",
    pathTemplate: "/api/tenants/current",
    description: "Returns the currently active tenant context.",
    authScope: "authenticated",
    verificationMode: "automated",
  },
  {
    id: "albums",
    category: "Gallery",
    method: "GET",
    pathTemplate: "/api/albums",
    description: "Lists albums visible to the active tenant context.",
    authScope: "tenant",
    verificationMode: "automated",
  },
  {
    id: "search",
    category: "Gallery",
    method: "GET",
    pathTemplate: "/api/search?albumId={sampleAlbumId}",
    description: "Searches media within an album using pagination.",
    authScope: "tenant",
    verificationMode: "automated",
  },
  {
    id: "media-detail",
    category: "Gallery",
    method: "GET",
    pathTemplate: "/api/media/{sampleMediaId}?albumId={sampleAlbumId}",
    description: "Returns detailed media metadata and a short-lived SAS URL.",
    authScope: "tenant",
    verificationMode: "automated",
  },
  {
    id: "media-download",
    category: "Gallery",
    method: "GET",
    pathTemplate: "/api/media/download?id={sampleMediaId}&albumId={sampleAlbumId}",
    description: "Streams a single media asset to the caller.",
    authScope: "tenant",
    verificationMode: "manual",
  },
  {
    id: "download-bulk",
    category: "Gallery",
    method: "POST",
    pathTemplate: "/api/download/bulk",
    description: "Streams a ZIP archive of multiple media assets.",
    authScope: "tenant",
    verificationMode: "manual",
    sampleBody: '{\n  "albumId": "{sampleAlbumId}",\n  "mediaIds": ["{sampleMediaId}"]\n}',
  },
  {
    id: "media-delete",
    category: "Gallery",
    method: "DELETE",
    pathTemplate: "/api/media/{sampleMediaId}?albumId={sampleAlbumId}",
    description: "Deletes a media item from the active tenant album.",
    authScope: "contributor",
    verificationMode: "manual",
    destructive: true,
  },
  {
    id: "admin-stats",
    category: "Admin",
    method: "GET",
    pathTemplate: "/api/admin/stats",
    description: "Platform-wide administrative summary metrics.",
    authScope: "platformAdmin",
    verificationMode: "automated",
  },
  {
    id: "admin-audit",
    category: "Admin",
    method: "GET",
    pathTemplate: "/api/admin/audit",
    description: "Paginated audit log retrieval for platform administrators.",
    authScope: "platformAdmin",
    verificationMode: "automated",
  },
  {
    id: "admin-users",
    category: "Admin",
    method: "GET",
    pathTemplate: "/api/admin/users",
    description: "Lists users visible to the platform admin surface.",
    authScope: "platformAdmin",
    verificationMode: "automated",
  },
  {
    id: "admin-users-action",
    category: "Admin",
    method: "POST",
    pathTemplate: "/api/admin/users",
    description: "Blocks or unblocks a user account.",
    authScope: "platformAdmin",
    verificationMode: "manual",
    destructive: true,
    sampleBody: '{\n  "email": "operator@example.com",\n  "action": "block"\n}',
  },
  {
    id: "admin-users-promote",
    category: "Admin",
    method: "PATCH",
    pathTemplate: "/api/admin/users",
    description: "Promotes or demotes a platform administrator.",
    authScope: "platformAdmin",
    verificationMode: "manual",
    destructive: true,
    sampleBody: '{\n  "email": "operator@example.com",\n  "isPlatformAdmin": true\n}',
  },
  {
    id: "admin-set-password",
    category: "Admin",
    method: "POST",
    pathTemplate: "/api/admin/users/set-password",
    description: "Sets a password for an existing user record.",
    authScope: "platformAdmin",
    verificationMode: "manual",
    destructive: true,
    sampleBody: '{\n  "email": "operator@example.com",\n  "password": "redacted"\n}',
  },
  {
    id: "admin-tenants",
    category: "Admin",
    method: "GET",
    pathTemplate: "/api/admin/tenants",
    description: "Lists tenant organizations visible to platform administrators.",
    authScope: "platformAdmin",
    verificationMode: "automated",
  },
  {
    id: "admin-tenants-create",
    category: "Admin",
    method: "POST",
    pathTemplate: "/api/admin/tenants",
    description: "Creates a new tenant organization.",
    authScope: "platformAdmin",
    verificationMode: "manual",
    destructive: true,
    sampleBody:
      '{\n  "name": "Example Tenant",\n  "slug": "example-tenant",\n  "isPublic": false,\n  "description": "Example tenant for verification."\n}',
  },
  {
    id: "admin-tenants-update",
    category: "Admin",
    method: "PATCH",
    pathTemplate: "/api/admin/tenants?id={activeTenantId}",
    description: "Updates tenant metadata and branding.",
    authScope: "platformAdmin",
    verificationMode: "manual",
    destructive: true,
    sampleBody: '{\n  "description": "Updated from API verification console."\n}',
  },
  {
    id: "admin-tenants-delete",
    category: "Admin",
    method: "DELETE",
    pathTemplate: "/api/admin/tenants?id={activeTenantId}",
    description: "Deactivates a tenant organization.",
    authScope: "platformAdmin",
    verificationMode: "manual",
    destructive: true,
  },
  {
    id: "admin-albums",
    category: "Tenant Admin",
    method: "GET",
    pathTemplate: "/api/admin/albums?tenantId={activeTenantId}",
    description: "Lists albums for the active tenant admin context.",
    authScope: "tenantAdmin",
    verificationMode: "automated",
  },
  {
    id: "admin-albums-create",
    category: "Tenant Admin",
    method: "POST",
    pathTemplate: "/api/admin/albums",
    description: "Creates an album in the active tenant.",
    authScope: "tenantAdmin",
    verificationMode: "manual",
    destructive: true,
    sampleBody: '{\n  "name": "Verification Album",\n  "description": "Created from API test console."\n}',
  },
  {
    id: "admin-albums-update",
    category: "Tenant Admin",
    method: "PATCH",
    pathTemplate: "/api/admin/albums?id={sampleAlbumId}",
    description: "Updates album metadata and cover image.",
    authScope: "tenantAdmin",
    verificationMode: "manual",
    destructive: true,
    sampleBody: '{\n  "description": "Updated from API test console."\n}',
  },
  {
    id: "admin-albums-delete",
    category: "Tenant Admin",
    method: "DELETE",
    pathTemplate: "/api/admin/albums?id={sampleAlbumId}",
    description: "Soft-deletes an album and its media.",
    authScope: "tenantAdmin",
    verificationMode: "manual",
    destructive: true,
  },
  {
    id: "admin-members",
    category: "Tenant Admin",
    method: "GET",
    pathTemplate: "/api/admin/members?tenantId={activeTenantId}",
    description: "Lists tenant members and their roles.",
    authScope: "tenantAdmin",
    verificationMode: "automated",
  },
  {
    id: "admin-members-add",
    category: "Tenant Admin",
    method: "POST",
    pathTemplate: "/api/admin/members?tenantId={activeTenantId}",
    description: "Adds or reactivates a tenant member.",
    authScope: "tenantAdmin",
    verificationMode: "manual",
    destructive: true,
    sampleBody: '{\n  "userEmail": "operator@example.com",\n  "role": "viewer"\n}',
  },
  {
    id: "admin-members-update",
    category: "Tenant Admin",
    method: "PATCH",
    pathTemplate: "/api/admin/members?tenantId={activeTenantId}",
    description: "Changes a tenant member role.",
    authScope: "tenantAdmin",
    verificationMode: "manual",
    destructive: true,
    sampleBody: '{\n  "email": "operator@example.com",\n  "role": "admin"\n}',
  },
  {
    id: "admin-members-delete",
    category: "Tenant Admin",
    method: "DELETE",
    pathTemplate: "/api/admin/members?tenantId={activeTenantId}&email=operator@example.com",
    description: "Removes a tenant member.",
    authScope: "tenantAdmin",
    verificationMode: "manual",
    destructive: true,
  },
  {
    id: "admin-domains",
    category: "Tenant Admin",
    method: "GET",
    pathTemplate: "/api/admin/domains?tenantId={activeTenantId}",
    description: "Lists allowed email domains for a tenant.",
    authScope: "tenantAdmin",
    verificationMode: "automated",
  },
  {
    id: "admin-domains-add",
    category: "Tenant Admin",
    method: "POST",
    pathTemplate: "/api/admin/domains?tenantId={activeTenantId}",
    description: "Adds an allowed domain for automatic viewer access.",
    authScope: "tenantAdmin",
    verificationMode: "manual",
    destructive: true,
    sampleBody: '{\n  "domain": "example.com"\n}',
  },
  {
    id: "admin-domains-delete",
    category: "Tenant Admin",
    method: "DELETE",
    pathTemplate: "/api/admin/domains?tenantId={activeTenantId}&id=domain-record-id",
    description: "Deactivates an allowed domain.",
    authScope: "tenantAdmin",
    verificationMode: "manual",
    destructive: true,
  },
  {
    id: "admin-upload",
    category: "Tenant Admin",
    method: "POST",
    pathTemplate: "/api/admin/upload",
    description: "Uploads a media file to an album in the active tenant.",
    authScope: "contributor",
    verificationMode: "manual",
    destructive: true,
    sampleBody: "{\n  \"formData\": \"binary upload required\"\n}",
  },
];

export interface ProbeSamples {
  activeTenantId?: string;
  activeTenantSlug?: string;
  sampleAlbumId?: string;
  sampleMediaId?: string;
}

export function resolvePathTemplate(
  pathTemplate: string,
  samples: ProbeSamples
): string | null {
  const replacements: Record<string, string | undefined> = {
    "{activeTenantId}": samples.activeTenantId,
    "{activeTenantSlug}": samples.activeTenantSlug,
    "{sampleAlbumId}": samples.sampleAlbumId,
    "{sampleMediaId}": samples.sampleMediaId,
  };

  let resolved = pathTemplate;
  for (const [token, value] of Object.entries(replacements)) {
    if (!resolved.includes(token)) continue;
    if (!value) return null;
    resolved = resolved.replaceAll(token, encodeURIComponent(value));
  }

  return resolved;
}
